version: "3"

services:
  php-fpm:
    container_name: test-php
    build: ./php-fpm
    volumes:
      - ./application:/var/www/html
  postgres:
    container_name: test-postgres
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
  nginx:
    container_name: test-nginx
    image: nginx:1
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./application:/var/www/html
    ports:
      - "80:80"
  adminer:
    container_name: test-adminer
    image: adminer
    ports:
      - "8080:8080"
